GET http://localhost:3000/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lIjo5MDQ4NzUyNjkxLCJwYXNzd29yZCI6IiQyYiQxMCQ0cUtlQllDOUs4NHZUOFd2V1Fiai9lSlQ0VmF5VHlVL2pZT2l2WkpHV000ZnRTUkR5Z2dpUyIsImlhdCI6MTY3ODAxMzQwMywiZXhwIjoxNjc4MDE3MDAzfQ.RG7czRFB0dF3HoeQEF6twa6TGWsZCyfNjxhUzzWWzM0


### user edit page
GET http://localhost:3000/admin/userDetails HTTP/1.1
Content-Type: application/json


### costumers
GET http://localhost:3000/admin/costumers HTTP/1.1
Content-Type: application/json


###
GET http://localhost:3000/signup HTTP/1.1
Content-Type: application/json


### user :- signup
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "name":"",
    "email":"six@gmail.com",
    "phone":900006,
    "password":"hello123"
}

### user :- login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email":"test1@gmail.com",
    "password":"12345678"
}

### admin :- login
POST http://localhost:3000/admin/login HTTP/1.1
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"admin123"
}

### admin :- create user test
POST http://localhost:3000/admin/create/user HTTP/1.1
Content-Type: application/json

{
    "name":"todelete",
    "email":"todelete@gmail.com",
    "phone":98634095,
    "password":"hello"
}

### admin :- update user data
PUT http://localhost:3000/admin/update/user_data?id=63fec955ee25bde3204efadd HTTP/1.1
Content-Type: application/json

{
    "name":"use",
    "email":"use@gmail.com",
    "phone":539820358
}

### admin :- user deletion
DELETE http://localhost:3000/admin/delete/user HTTP/1.1
Content-Type: application/json

{
    "id":"63fb8e9ae9008dd26a9f417a"
}